# Generated by Django 5.2.6 on 2025-09-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
            ],
        ),
    ]
