# Generated by Django 5.2.6 on 2025-09-30 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('CONVERSION', 'Conversion')], max_length=10)),
                ('transactionDate', models.DateTimeField(auto_now_add=True)),
                ('amountReceived', models.DecimalField(decimal_places=2, max_digits=20)),
                ('receivingCurrency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
    ]
