# Generated by Django 5.2.6 on 2025-09-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbalance',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
