# Generated by Django 5.2.6 on 2025-09-26 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('card_reference', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(default='virtual', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('holder_name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=2)),
                ('first_six', models.CharField(max_length=6)),
                ('last_four', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
